categories = ["⚡IKAR",
              '📚 Factor books kitoblari',
              "Biznes kitoblar",
              "Diniy kitoblar",
              "📚 Boshqa kitoblar",
              "Psixologik kitoblar",
              "Tarbiyaviy-oilaviy kitoblar",
              "TUrk badiiy-ma'rifiy kitoblar",
              "Badiiy romanlar",
              "Qissa va romanlar",
              "Badiiy kitoblar va qissalar",
              ]
